### ISSUE TITLE
tibble/Kable error

### ISSUE THREAD

**Issue by rtabandera** [NOAA-EDAB/esp_data_aggregation#13]
In 4.3 B/Bmsy the tibble is not displayed properly 

![image](https://user-images.githubusercontent.com/64960823/108434718-3b893380-71ec-11eb-8e20-79b87a686bb5.png)

**Comment by atyrell3** [comment]
Oops, that was part of some troubleshooting I was doing last week. I removed it and the fix is in my most recent pull request.
